version: "3.8"
services:
  app:
    image: golang:1.17.3-bullseye
    ports:
      - 8080:8080
    working_dir: /src
    volumes:
      - ./:/src
    depends_on:
        - mysql
    command: sh -c "cd ./src && ./wait-for-it.sh mysql:3306 -q && go build && ./questionandanswer"
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: 123456123456
      MYSQL_DB: questionandanswer
  mysql:
    image: mysql:8.0
    ports:
      - 3306:3306
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: 123456123456
      MYSQL_DATABASE: questionandanswer
    command: --init-file /database/create_tables.sql
    volumes:
        - ./database/create_tables.sql:/database/create_tables.sql